### ISSUE TITLE
pytest-twisted 1.8 not playing well with pytest 4.1

### ISSUE THREAD

**Issue by ThreePinkApples** [pytest-dev/pytest-twisted#44]
```
Running tests
INTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "/home/oheddela/.virtualenvs/default/lib/python3.6/site-packages/_pytest/main.py", line 203, in wrap_session
INTERNALERROR>     session.exitstatus = doit(config, session) or 0
INTERNALERROR>   File "/home/oheddela/.virtualenvs/default/lib/python3.6/site-packages/_pytest/main.py", line 242, in _main
INTERNALERROR>     config.hook.pytest_collection(session=session)
INTERNALERROR>   File "/home/oheddela/.virtualenvs/default/lib/python3.6/site-packages/pluggy/hooks.py", line 284, in __call__
INTERNALERROR>     return self._hookexec(self, self.get_hookimpls(), kwargs)
INTERNALERROR>   File "/home/oheddela/.virtualenvs/default/lib/python3.6/site-packages/pluggy/manager.py", line 67, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
INTERNALERROR>   File "/home/oheddela/.virtualenvs/default/lib/python3.6/site-packages/pluggy/manager.py", line 61, in <lambda>
INTERNALERROR>     firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
INTERNALERROR>   File "/home/oheddela/.virtualenvs/default/lib/python3.6/site-packages/pluggy/callers.py", line 208, in _multicall
INTERNALERROR>     return outcome.get_result()
INTERNALERROR>   File "/home/oheddela/.virtualenvs/default/lib/python3.6/site-packages/pluggy/callers.py", line 80, in get_result
INTERNALERROR>     raise ex[1].with_traceback(ex[2])
INTERNALERROR>   File "/home/oheddela/.virtualenvs/default/lib/python3.6/site-packages/pluggy/callers.py", line 187, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "/home/oheddela/.virtualenvs/default/lib/python3.6/site-packages/_pytest/main.py", line 252, in pytest_collection
INTERNALERROR>     return session.perform_collect()
INTERNALERROR>   File "/home/oheddela/.virtualenvs/default/lib/python3.6/site-packages/_pytest/main.py", line 466, in perform_collect
INTERNALERROR>     self.config.pluginmanager.check_pending()
INTERNALERROR>   File "/home/oheddela/.virtualenvs/default/lib/python3.6/site-packages/pluggy/manager.py", line 250, in check_pending
INTERNALERROR>     % (name, hookimpl.plugin),
INTERNALERROR> pluggy.manager.PluginValidationError: unknown hook 'pytest_namespace' in plugin <module 'pytest_twisted' from '/home/oheddela/.virtualenvs/default/lib/python3.6/site-packages/pytest_twisted.py'>
```

**Comment by nicoddemus** [comment]
Thanks, opened https://github.com/pytest-dev/pytest-twisted/pull/45 with a fix. 👍

**Comment by altendky** [comment]
Thank you both.  Not that I have any doubts about the fixes but I'll look this over when I get home.

@nicoddemus, any thoughts on https://github.com/pytest-dev/pytest-twisted/issues/42#issuecomment-443256045 ?

I should setup daily builds with actual CI (dependencies at release, prerelease, and vcs) and make sure we see deprecation warnings.

**Comment by nicoddemus** [comment]
> I should setup daily builds with actual CI (dependencies at release, prerelease, and vcs) and make sure we see deprecation warnings.

Sounds good. I suggest to add `filterwarnings=error` to your `pytest.ini`, which will effectively change warnings into errors. 👍
